### ISSUE TITLE
can't deploy kindnet outside of kind

### ISSUE THREAD

**Issue by lazywhite** [aojea/kindnet#16]
It seems kindnet can work only in kind clusters?  can we use it as a standalone cni like calico or flannel? 

I just installed kindnet on k3s, it gives this error
```
Defaulted container "kindnet-cni" out of: kindnet-cni, install-cni-bin (init)
I1221 13:01:31.319885       1 main.go:78] hostIP = 10.1.199.96
podIP = 10.1.199.96
I1221 13:01:31.320158       1 main.go:87] setting mtu 0 for CNI 
I1221 13:01:31.320163       1 main.go:89] Failed to get MTU size from interface eth0, using kernel default MTU size error:Found no eth0 device
I1221 13:01:31.320172       1 main.go:105] Configuring CNI path: /etc/cni/net.d/10-kindnet.conflist bridge: true disableOffload: false mtu: 0
ERROR: configmaps "kubeadm-config" not found
ERROR: configmaps "kube-proxy" not found
panic: Cluster CIDR is not defined

goroutine 1 [running]:
main.main()
	/src/cmd/kindnetd/main.go:119 +0xdd9
```

**Comment by BenTheElder** [comment]
> ERROR: configmaps "kubeadm-config" not found
> ERROR: configmaps "kube-proxy" not found

Those come from kubeadm, and are used to discover cluster networking configuration.
You can set some legacy environment variables instead. https://github.com/aojea/kindnet/blob/b5a3f87afe47979bea845cad13c7cc6478a901de/cmd/kindnetd/subnets.go#L74-L75

kubeadm aside, kindnet aims to support Kubernetes, k3s may not work.

**Comment by aojea** [comment]
What Ben says
