### ISSUE TITLE
Need a way to specify rangeStart 

### ISSUE THREAD

**Issue by dims** [aojea/kindnet#47]
So, in kubernetes EC2 test harness when we use 172.31.0.0/24 as the VPC then 172.31.0.2 is the DNS ip address

Given, `The IP address of the DNS server is the base of the VPC network range plus two.` in general, we need a way to skip using `rangeStart`. When we don't and the coredns pod gets the same ip address as the VPC DNS, there is a `loop` https://coredns.io/plugins/loop/#troubleshooting and the coredns pod ends up crash looping endlessly

- https://www.reddit.com/r/aws/comments/pryrk8/what_ip_is_the_dns_for_vpcsubnet/
- https://docs.aws.amazon.com/vpc/latest/userguide/subnet-sizing.html

Example:
```
{
	"cniVersion": "0.4.0",
	"name": "kindnet",
	"plugins": [
		{
			"type": "ptp",
			"ipMasq": false,
			"ipam": {
				"type": "host-local",
				"dataDir": "/run/cni-ipam-state",
				"routes": [
					{ "dst": "0.0.0.0/0" }
				],
				"ranges": [
					[
						{ 
							"subnet": "172.31.0.0/24",
							"rangeStart": "172.31.0.3"  // Start allocation from 172.31.0.3
						}
					]
				]
			}
		},
		{
			"type": "portmap",
			"capabilities": {
				"portMappings": true
			}
		}
	]
}
```

**Comment by dims** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/126255

**Comment by aojea** [comment]
will be fixed in https://github.com/aojea/kindnet/issues/47
